# NOTE: Generated By HttpRunner v4.3.5
# FROM: all.yml
from httprunner import HttpRunner, Config, Step, RunRequest

class TestCaseAll(HttpRunner):

    

    config = Config("testcase description")

    teststeps = [
        
            Step(RunRequest("/login_nsr").post("http://10.199.20.221:38080/login_nsr").with_headers(**{'Content-Type': 'multipart/form-data; boundary=--------------------------635016838411740928539573', 'Postman-Token': '91f87f33-91c2-4fb0-bb56-70ceeb625651', 'User-Agent': 'PostmanRuntime/7.32.3'}).with_data("----------------------------635016838411740928539573
Content-Disposition: form-data; name="djxh"

10000000333000000118
----------------------------635016838411740928539573
Content-Disposition: form-data; name="nsrsbh"

433333333333333477
----------------------------635016838411740928539573--
").validate().assert_equal("status_code", 200).assert_equal('headers."Content-Type"', "text/html;charset=UTF-8")),
        
            Step(RunRequest("/yhs-web/api/bsjd/query/list").post("http://10.199.20.221:8081/yhs-web/api/bsjd/query/list").with_headers(**{'Content-Type': 'application/json;charset=UTF-8', 'Postman-Token': 'a48ceb88-21ba-4689-b01c-703a303b79a4', 'User-Agent': 'PostmanRuntime/7.32.3'}).with_json({'bsjd': '', 'bsjdlx': '', 'fromtc': '', 'kqhDjxh': '', 'rqq': '2023-05-04', 'rqz': '2023-08-25', 'rwmc': '', 'sfsbDm': ''}).validate().assert_equal("status_code", 200).assert_equal('headers."Content-Type"', "application/json;charset=UTF-8").assert_equal("body.message", None).assert_equal("body.success", True).assert_equal("body.msgCode", None).assert_equal("body.msgParams", None)),
        
    ]

if __name__ == "__main__":
    TestCaseAll().test_start()
